apiVersion: apps/v1
kind: deployment
metadata:
  name: java-spring-deployment
spec:
  selector:
    matchLabels:
      app: java-spring
  replicas: 2
  template:
    metadata:
      labels:
        app: java-spring
    spec:
      containers:
      - name: java-spring
        image: myapp:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1  
kind: service
metadata:
  name: java-spring-service
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: java-spring
